### ISSUE TITLE
Stops working with newest redis client

### ISSUE THREAD

**Issue by krazik** [wankdanker/node-redis-jsonify#4]
from redis      ^2.6.0-0  to  ^2.6.0-1  

all my objects started getting serialized as strings, tho parse still works if they're already in redis as json object.

**Comment by Dillybob92** [comment]
Can confirm here too.

**Comment by wankdanker** [comment]
This module proxies node_redis' `send_command` function. Looks like in these newer versions that function is now called `internal_send_command`. (https://github.com/NodeRedis/node_redis/blob/v.2.6.0-1/index.js#L749).

We'll probably have to take a different approach going forward and proxy all of the exposed methods by iterating the commands available in the `redis-commands` module. That way we can avoid tracking the internal changes. The downside of that is possibly having to deal with the variation of arguments passed to the various methods.

Anyway I just tested proxying the `internal_send_command` in addition to `send_command` (whichever is available)  and it seems to work. The tests pass anyway...

If you both would like to give it a shot, it's on npm: redis-jsonfiy@1.0.0

**Comment by krazik** [comment]
thanks!

**Comment by Dillybob92** [comment]
Can confirm working now!! Thank you WankDanker, that was quick!
