### ISSUE TITLE
Issue when run Redis 

### ISSUE THREAD

**Issue by nhoctanker** [wankdanker/node-redis-jsonify#5]
http://prntscr.com/bddbqm

**Comment by mkalish** [comment]
I ran into the same issue.  Seems to be be caused by the recent node-redis 2.6 release where the api for commands has changed.

**Comment by wankdanker** [comment]
Is everything broken? Or just certain commands?

**Comment by mkalish** [comment]
From my quick examination, it seems that the command, arguments and callback are passed in as a single object rather than three arguments.  Reverting redis dependency to 2.5 worked for me

**Comment by jhlee8804** [comment]
Same issue in Redis 3.2.100

**Comment by jamesopti** [comment]
Same here on Redis 3.2.4
